# Generated by Django 4.2.20 on 2025-03-22 10:54

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("notion", "0013_video_title"),
        ("products", "0033_ProductGroupDashamail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[],
            options={
                "ordering": ["-created"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.course",),
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField(db_index=True, default=0)),
                ("hidden", models.BooleanField(default=True, help_text="Users can't find such materials in the listing", verbose_name="Hidden")),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="lessons", to="products.course")),
                ("material", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to="notion.material")),
            ],
            options={
                "ordering": ["position"],
                "indexes": [models.Index(fields=["course", "position"], name="lessons_les_course__6bd811_idx")],
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
    ]
