# Generated by Django 3.2.10 on 2022-01-08 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0018_ProductGroups"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("page_id", models.CharField(db_index=True, help_text="Paste it from apps.notion address bar", max_length=64, verbose_name="Notion page id")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.course")),
            ],
            options={
                "verbose_name": "Notion material",
                "verbose_name_plural": "Notion materials",
                "permissions": [("see_all_materials", "May access materials from every course")],
            },
        ),
        migrations.AddConstraint(
            model_name="material",
            constraint=models.UniqueConstraint(fields=("course", "page_id"), name="single_page_per_single_course"),
        ),
    ]
