# Generated by Django 4.1.9 on 2023-06-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notion", "0005_MaterailFiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionCacheEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("cache_key", models.CharField(db_index=True, max_length=255, unique=True)),
                ("content", models.JSONField()),
                ("expires", models.DateTimeField(db_index=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
