# Generated by Django 4.2.8 on 2023-12-17 17:26

from django.db import migrations, models

import core.files
import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("notion", "0006_NotionCacheEntry"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("url", models.URLField(db_index=True, max_length=1024, unique=True)),
                ("file", models.FileField(unique=True, upload_to=core.files.RandomFileName("assets"))),
            ],
            options={
                "verbose_name": "Notion asset",
                "verbose_name_plural": "Notion assets",
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
    ]
