# Generated by Django 4.2.8 on 2023-12-21 11:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("notion", "0007_notion_asset"),
    ]

    operations = [
        migrations.AddField(
            model_name="notionasset",
            name="md5_sum",
            field=models.CharField(default="", max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notionasset",
            name="size",
            field=models.IntegerField(default=0, verbose_name="Image size in bytes"),
            preserve_default=False,
        ),
    ]
