# Generated by Django 4.2.15 on 2024-08-30 17:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notion", "0008_notion_asset_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="slug",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True, verbose_name="Our page id"),
        ),
    ]
