# Generated by Django 4.2.15 on 2024-09-04 07:38

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("notion", "0009_notion_slug_field_translation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("youtube_id", models.CharField(db_index=True, max_length=32, unique=True)),
                ("rutube_id", models.CharField(blank=True, db_index=True, max_length=32, null=True)),
            ],
            options={
                "verbose_name": "Notion video",
                "verbose_name_plural": "Notion videos",
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
    ]
