# Generated by Django 4.2.15 on 2024-09-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notion", "0010_notion_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="rutube_id",
            field=models.CharField(blank=True, db_index=True, help_text="Paste it from the address bar", max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="youtube_id",
            field=models.CharField(db_index=True, help_text="Paste it from the address bar", max_length=256, unique=True),
        ),
    ]
