# Generated by Django 4.2.16 on 2024-09-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notion", "0011_notion_video_fields_and_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="rutube_access_key",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="rutube_id",
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="youtube_id",
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
