# Generated by Django 4.2.16 on 2024-09-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notion", "0012_video_rutube_access_key_alter_video_rutube_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="title",
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name="Title"),
        ),
    ]
