# Generated by Django 4.2.20 on 2025-03-22 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notion", "0014_page_links"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notioncacheentry",
            old_name="cache_key",
            new_name="page_id",
        ),
    ]
