# Generated by Django 5.2.7 on 2025-11-12 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notion", "0015_better_cache_key_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notioncacheentry",
            name="expires",
        ),
    ]
