# Generated by Django 5.2.7 on 2025-11-12 14:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0016_removed_cache_expiration'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotionCacheEntryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('page_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('fetch_started', models.DateTimeField(db_index=True, null=True)),
                ('fetch_complete', models.DateTimeField(db_index=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
    ]
