# Generated by Django 4.2.23 on 2025-07-17 16:57
from decimal import Decimal

from django.db import migrations, models


def set_default_rate_for_past_deals(apps, schema_editor):  # NOQA: ARG001
    apps.get_model("b2b.Deal").objects.update(currency_rate_on_creation=Decimal(1))


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "RUB"), ("USD", "USD"), ("KZT", "KZT"), ("KIS", "KIS (for zero-price orders)")], default="RUB", verbose_name="Currency"
            ),
        ),
        migrations.AddField(
            model_name="deal",
            name="currency_rate_on_creation",
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
        migrations.RunPython(set_default_rate_for_past_deals),
    ]
