# Generated by Django 4.2.23 on 2025-07-15 12:34

import django.db.models.deletion
from django.db import migrations, models


def set_ruble_currency_to_past_deals(apps, schema_editor) -> None:  # NOQA: ARG001
    rub, _ = apps.get_model("banking.Currency").objects.get_or_create(
        name="RUB",
        rate=1,
    )
    apps.get_model("b2b.Deal").objects.update(currency=rub)


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0005_rename_currency_model"),
        ("b2b", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="currency",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="banking.currency", verbose_name="Currency"),
        ),
        migrations.RunPython(set_ruble_currency_to_past_deals),
        migrations.AlterField(
            model_name="deal",
            name="currency",
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.PROTECT, to="banking.currency", verbose_name="Currency"),
        ),
    ]
