# Generated by Django 4.2.23 on 2025-07-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "RUB"), ("USD", "USD"), ("KZT", "KZT"), ("KIS", "KIS (for zero-price orders)")], default="RUB", verbose_name="Currency"
            ),
        ),
    ]
