# Generated by Django 5.2.7 on 2025-10-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0002_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="currency",
            field=models.CharField(
                choices=[("RUB", "RUB"), ("USD", "USD"), ("EUR", "EUR"), ("KZT", "KZT"), ("KIS", "KIS (for zero-price orders)")],
                default="RUB",
                verbose_name="Currency",
            ),
        ),
    ]
