# Generated by Django 4.2.20 on 2025-03-08 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0002_fix_student_relation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="deal",
            old_name="product",
            new_name="course",
        ),
    ]
