# Generated by Django 4.2.20 on 2025-03-09 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0003_fix_naming"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="customer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="b2b.customer", verbose_name="Customer"),
        ),
    ]
