# Generated by Django 5.2.7 on 2025-11-03 17:18

from django.db import migrations, models

import apps.b2b.models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0003_euro"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="tin",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                unique=True,
                validators=[apps.b2b.models.customer.validate_customer_code],
                verbose_name="TIN",
            ),
        ),
    ]
