# Generated by Django 4.2.5 on 2023-10-22 14:47

from django.core.exceptions import ValidationError
from django.db import migrations
from django.db import models
from django.db.models.fields import json


def retrieve_and_set_event_type_payment_intent(apps, schema_editor):
    StripeNotification = apps.get_model("stripebank", "StripeNotification")

    if StripeNotification.objects.exclude(raw__type="checkout.session.completed").exists():
        raise ValidationError("Only 'checkout.session.completed' events could be proceeded")

    StripeNotification.objects.update(
        event_type=json.KT("raw__type"),
        payment_intent=json.KT("raw__data__object__payment_intent"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("stripebank", "0002_OrderUUID"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stripenotification",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="stripenotification",
            name="status",
        ),
        migrations.AddField(
            model_name="stripenotification",
            name="event_type",
            field=models.CharField(db_index=True, default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stripenotification",
            name="payment_intent",
            field=models.CharField(db_index=True, default="", max_length=256),
            preserve_default=False,
        ),
        migrations.RunPython(retrieve_and_set_event_type_payment_intent),
    ]
