# Generated by Django 3.1.8 on 2021-05-01 23:33

import uuid

from django.db import migrations
from django.db import models


def set_random_uuid_for_all_users(apps, schema_editor):
    for user in apps.get_model('users.User').objects.filter(uuid__isnull=True).iterator():
        user.uuid = uuid.uuid4()
        user.save(update_fields=['uuid'])


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_NamesInEnglish'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.RunPython(set_random_uuid_for_all_users),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),

    ]
