# Generated by Django 3.2.16 on 2022-12-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_AddtionalProfileFields"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_username",
            field=models.CharField(blank=True, db_index=True, default="", max_length=256),
        ),
    ]
