# Generated by Django 4.1.9 on 2023-07-07 10:17

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_drop_linkedin_github_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), default=list, size=None),
        ),
        migrations.AddIndex(
            model_name="user",
            index=django.contrib.postgres.indexes.GinIndex(fields=["tags"], name="users_user_tags_d41b16_gin"),
        ),
    ]
