# Generated by Django 4.2.13 on 2024-06-13 15:33

from django.db import migrations, models

import core.files


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_TagsForUser"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to=core.files.RandomFileName("users/avatars"), verbose_name="Avatar"),
        ),
    ]
