# Generated by Django 4.2.23 on 2025-06-26 08:48

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_UserAvatar"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
        migrations.CreateModel(
            name="AdminUserProxy",
            fields=[],
            options={
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
