# Generated by Django 4.2.23 on 2025-08-11 12:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_admin_user_proxy_model_rename"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscribed",
        ),
    ]
