# Generated by Django 5.2.7 on 2025-11-05 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_dropped_subscribe_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-pk"], "verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
