# Generated by Django 5.2.7 on 2025-12-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_user_indices"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name="Rank"),
        ),
        migrations.AddField(
            model_name="user",
            name="rank_label_color",
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name="Rank label color"),
        ),
    ]
