# Generated by Django 5.2.7 on 2025-12-06 18:44

from django.db import migrations, models

import apps.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_user_rank"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="rank_label_color",
            field=models.CharField(blank=True, max_length=7, null=True, validators=[apps.users.models.validate_hex_color], verbose_name="Rank label color"),
        ),
    ]
