# Generated by Django 5.2.7 on 2025-12-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_rank_label_validator"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="random_name",
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name="Randomly generated name"),
        ),
    ]
