# Generated by Django 5.2.11 on 2026-02-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0018_random_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="always_display_comments",
            field=models.BooleanField(default=False, help_text="Useful for course experts", verbose_name="Always display comments"),
        ),
    ]
