# Generated by Django 3.1.6 on 2021-02-06 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0012_DesiredBankString'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('bank', models.CharField(choices=[('tinkoff_bank', 'TinkoffBank'), ('tinkoff_credit', 'TinkoffCredit')], db_index=True, max_length=32, verbose_name='Bank id')),
                ('bank_request_id', models.CharField(db_index=True, max_length=256, verbose_name='Internal bank request id')),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('signed', 'Signed')], db_index=True, default='new', max_length=32)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
            ],
            options={
                'verbose_name': 'Bank credit',
                'verbose_name_plural': 'Bank credits',
            },
        ),
        migrations.AddIndex(
            model_name='credit',
            index=models.Index(fields=['order', 'bank', 'bank_request_id'], name='banking_cre_order_i_f1ab35_idx'),
        ),
        migrations.AddConstraint(
            model_name='credit',
            constraint=models.UniqueConstraint(fields=('order', 'bank', 'bank_request_id'), name='Single request to single bank within one order'),
        ),
    ]
