# Generated by Django 4.2.5 on 2023-09-18 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Receipt",
        ),
    ]
