# Generated by Django 3.2.12 on 2022-03-16 21:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0001_Initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chain',
            options={'verbose_name': 'Email chain', 'verbose_name_plural': 'Email chains'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Email chain message', 'verbose_name_plural': 'Email chain messages'},
        ),
        migrations.AddField(
            model_name='chain',
            name='sending_is_active',
            field=models.BooleanField(default=False),
        ),
    ]
