# Generated by Django 3.2.17 on 2023-02-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0010_ChainsAdminLabelChange'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='The chain is archived'),
        ),
    ]
