# Generated by Django 4.1.10 on 2023-07-12 09:37
from django.db import migrations
from django.db import models


def populate_with_default_domains(apps, schema_editor):
    personal_domains = (
        "gmail.com",
        "icloud.com",
        "hotmail.com",
        "hey.com",
        "mail.ru",
        "list.ru",
        "bk.ru",
        "inbox.ru",
        "pm.me",
        "protonmail.com",
        "yandex.ru",
        "ya.ru",
        "rambler.ru",
        "riseup.net",
    )
    PersonalEmailDomain = apps.get_model("mailing", "PersonalEmailDomain")

    for domain in personal_domains:
        PersonalEmailDomain.objects.create(name=domain)


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0003_CustomReplyTo"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalEmailDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=20, unique=True)),
            ],
            options={
                "verbose_name": "Personal email domain",
                "verbose_name_plural": "Personal email domains",
            },
        ),
        migrations.RunPython(populate_with_default_domains),
    ]
