# Generated by Django 4.2.5 on 2023-09-06 16:41

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0004_PersonalEmailDomain"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="emaillogentry",
            index=models.Index(fields=["email", "template_id"], name="mailing_ema_email_d5d544_idx"),
        ),
        migrations.AddConstraint(
            model_name="emaillogentry",
            constraint=models.UniqueConstraint(fields=("email", "template_id"), name="Single template per email"),
        ),
    ]
