from core.conf.environ import env

TINKOFF_TERMINAL_KEY = env("TINKOFF_TERMINAL_KEY", default=None)
TINKOFF_TERMINAL_PASSWORD = env("TINKOFF_TERMINAL_PASSWORD", default=None)
TINKOFF_CREDIT_SHOP_ID = env("TINKOFF_CREDIT_SHOP_ID", default=None)
TINKOFF_CREDIT_SHOWCASE_ID = env("TINKOFF_CREDIT_SHOWCASE_ID", default=None)

TINKOFF_CREDIT_DEMO_MODE = env("TINKOFF_CREDIT_DEMO_MODE", default=env("DEBUG"))

DOLYAME_LOGIN = env("DOLYAME_LOGIN", default=None)
DOLYAME_PASSWORD = env("DOLYAME_PASSWORD", default=None)
DOLYAME_CERTIFICATE_PATH = env("DOLYAME_CERTIFICATE_PATH", default="/dev/null")
