# Generated by Django 3.2.10 on 2022-01-09 18:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='title',
            field=models.CharField(blank=True, help_text='Will be fetched automatically if empty', max_length=128, verbose_name='Page title'),
        ),
    ]
