# Generated by Django 4.1.9 on 2023-06-23 09:24

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0005_MaterailFiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionCacheEntry",
            fields=[
                ("cache_key", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("value", models.TextField()),
                ("expires", models.DateTimeField(db_index=True)),
            ],
        ),
    ]
