# Generated by Django 4.1.9 on 2023-06-23 07:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0005_MaterailFiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotionCache",
            fields=[
                ("cache_key", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("value", models.TextField()),
                ("expires", models.DateTimeField()),
            ],
            options={
                "db_table": "notion_cache_table",
            },
        ),
        migrations.AddIndex(
            model_name="notioncache",
            index=models.Index(fields=["expires"], name="notion_cache_table_expires"),
        ),
    ]
