# Generated by Django 3.2.4 on 2021-06-03 19:53

import app.files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='image',
            field=models.ImageField(upload_to=app.files.RandomFileName('diplomas')),
        ),
    ]
