# Generated by Django 2.2.6 on 2019-11-03 19:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name_genitive',
            field=models.CharField('Genitive name', default='', max_length=255),
            preserve_default=False,
        ),
    ]
