# Generated by Django 2.2.7 on 2019-12-22 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_Bundles'),
        ('products', '0008_CustomTemplateId'),
    ]

    operations = [
    ]
