# Generated by Django 2.2.7 on 2020-01-12 14:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_merge_20191222_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='full_name',
            field=models.CharField(help_text='Билет на мастер-класс о TDD или «запись курсов кройки и шитья»', max_length=255, verbose_name='Full name for letters'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='name_receipt',
            field=models.CharField(help_text='«посещение мастер-класса по TDD» или «Доступ к записи курсов кройки и шитья»', max_length=255, verbose_name='Name for receipts'),
        ),
        migrations.AlterField(
            model_name='record',
            name='full_name',
            field=models.CharField(help_text='Билет на мастер-класс о TDD или «запись курсов кройки и шитья»', max_length=255, verbose_name='Full name for letters'),
        ),
        migrations.AlterField(
            model_name='record',
            name='name_receipt',
            field=models.CharField(help_text='«посещение мастер-класса по TDD» или «Доступ к записи курсов кройки и шитья»', max_length=255, verbose_name='Name for receipts'),
        ),
    ]
