# Generated by Django 2.2.7 on 2020-06-03 19:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_ZoomusWebinarId'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='template_id',
            field=models.CharField(blank=True, help_text='Leave it blank for the default template', max_length=256, null=True, verbose_name='Postmark template_id'),
        ),
    ]
