# Generated by Django 3.1.5 on 2021-01-09 15:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_GiftWelcomeLetterTemplateId'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='mailchimp_list_id',
            field=models.CharField(blank=True, help_text='Get it from audience settings', max_length=32, null=True, verbose_name='Mailchimp audience id'),
        ),
    ]
