# Generated by Django 3.2.12 on 2022-04-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_InternationalNames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='mailchimp_list_id',
        ),
    ]
