# Generated by Django 3.2.15 on 2022-09-21 14:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_CourseConfirmationTemplateId'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='confirmation_success_url',
            field=models.URLField(blank=True, null=True, verbose_name='Confirmation success URL'),
        ),
    ]
