# Generated by Django 4.1.9 on 2023-07-07 06:54

from django.db import migrations
from django.db import models

from app.helpers import slugify


def set_default_slug_to_group(apps, schema_editor):
    Group = apps.get_model("products", "Group")
    groups = Group.objects.all()
    for group in groups:
        group.slug = slugify(group.name)
        group.save()


def revert_set_default_slug_to_group(apps, schema_editor):
    Group = apps.get_model("products", "Group")
    Group.objects.update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0028_CourseCoverField"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="slug",
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(set_default_slug_to_group, reverse_code=revert_set_default_slug_to_group),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(null=False)
        ),
    ]
