# Generated by Django 4.1.10 on 2023-09-04 03:57

from django.db import migrations
from django.db import models


def move_amocrm_id_to_group(apps, schema_editor):
    for amocrm_group in apps.get_model("amocrm.AmoCRMProductGroup").objects.all().iterator():
        group = amocrm_group.group
        group.amocrm_id = amocrm_group.amocrm_id
        group.save()


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0031_DropGiftFields"),
        ("amocrm", "0008_Delete_separate_AmoCRMUserContact"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="amocrm_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(move_amocrm_id_to_group),
    ]
