# Generated by Django 4.2.5 on 2023-09-15 06:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0031_DropGiftFields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="zoomus_webinar_id",
        ),
    ]
