# Generated by Django 4.2.23 on 2025-08-14 10:55

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("a12n", "0002_PasswordlessTokensUsedDate"),
    ]

    operations = [
        migrations.CreateModel(
            name="JWTBlacklist",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("token", models.TextField(db_index=True, unique=True)),
            ],
            options={
                "verbose_name": "Blacklisted token",
                "verbose_name_plural": "Blacklisted tokens",
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
    ]
