# Generated by Django 3.2.12 on 2022-03-19 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0004_UniqueChainName"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="parent",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="children", to="chains.message"),
        ),
    ]
