# Generated by Django 3.2.12 on 2022-03-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0006_i18n"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="progress",
            index=models.Index(fields=["study", "message"], name="chains_prog_study_i_66bdd2_idx"),
        ),
        migrations.AddConstraint(
            model_name="progress",
            constraint=models.UniqueConstraint(fields=("study", "message"), name="single_message_per_study"),
        ),
    ]
