# Generated by Django 3.2.12 on 2022-03-20 19:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('chains', '0007_StudyConstraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='success',
            field=models.BooleanField(default=True),
        ),
    ]
