# Generated by Django 3.2.12 on 2022-03-22 16:57

from django.db import migrations

CHAINS = [
    2,
]

COURSES = [
    7,
]


def create_progress_records(apps, schema_editor):
    del schema_editor

    for message in apps.get_model("chains.Message").objects.filter(chain_id__in=CHAINS).iterator():
        for study in apps.get_model("studying.Study").objects.filter(course_id__in=COURSES).iterator():
            apps.get_model("chains.Progress").objects.get_or_create(message=message, study=study)


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0008_ChainProgressStatus"),
    ]

    operations = [
        migrations.RunPython(create_progress_records),
    ]
