# Generated by Django 3.2.12 on 2022-03-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0009_CreateChainProgressForAlreadyPurchasedUsers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="delay",
            field=models.BigIntegerField(default=0, help_text="1440 for day, 10080 for week", verbose_name="Delay (minutes)"),
        ),
    ]
