# Generated by Django 3.2.17 on 2023-02-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chains", "0010_ChainsAdminLabelChange"),
    ]

    operations = [
        migrations.AddField(
            model_name="chain",
            name="archived",
            field=models.BooleanField(default=False, verbose_name="The chain is archived"),
        ),
    ]
