# Generated by Django 4.1.7 on 2023-05-07 18:15

from django.db import migrations, models


def set_default_reply_to(apps, schema_editor):
    del schema_editor

    apps.get_model("mailing.EmailConfiguration").objects.filter(
        reply_to="",
    ).update(
        reply_to=models.F("from_email"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("mailing", "0002_EmailConfiguration"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailconfiguration",
            name="reply_to",
            field=models.CharField(default="", help_text="E.g. Fedor Borshev &lt;fedor@borshev.com&gt;", max_length=256, verbose_name="Email sender"),
            preserve_default=False,
        ),
        migrations.RunPython(set_default_reply_to),
        migrations.AlterField(
            model_name="emailconfiguration",
            name="reply_to",
            field=models.CharField(help_text="E.g. Fedor Borshev &lt;fedor@borshev.com&gt;", max_length=256, verbose_name="Reply-to header"),
        ),
    ]
