# Generated by Django 3.2.16 on 2022-12-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_AddtionalProfileFields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, db_index=True, default='', max_length=256),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_username', ''), _negated=True), fields=('telegram_username',), name='unique_telegram_username'),
        ),
    ]
