# Generated by Django 4.2.6 on 2023-10-30 16:35

from django.db import migrations
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_TagsForUser"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.UserManager()),
            ],
        ),
    ]
