# Generated by Django 2.2.13 on 2020-10-02 17:37

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLeadMagnetCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('slug', models.SlugField(unique=True)),
                ('template_id', models.CharField(help_text='Will be sent upon amocrm_lead registration', max_length=255,verbose_name='Letter template id')),
            ],
            options={
                'verbose_name': 'Email Lead Magnet Campaign',
                'verbose_name_plural': 'Email Lead Magnet Campaigns',
            },
        ),
    ]
