# Generated by Django 3.2.4 on 2021-06-03 15:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("studying", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Diploma",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("slug", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("language", models.CharField(choices=[("RU", "Russian"), ("EN", "English")], db_index=True, max_length=3)),
                ("image", models.ImageField(upload_to="")),
                ("study", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studying.study")),
            ],
            options={
                "verbose_name": "Diploma",
                "verbose_name_plural": "Diplomas",
                "ordering": ["-id"],
                "permissions": [("access_all_diplomas", "May access diplomas of all students")],
            },
        ),
        migrations.AddIndex(
            model_name="diploma",
            index=models.Index(fields=["study", "language"], name="diplomas_di_study_i_b71641_idx"),
        ),
        migrations.AddConstraint(
            model_name="diploma",
            constraint=models.UniqueConstraint(fields=("study", "language"), name="unique_study"),
        ),
    ]
