# Generated by Django 3.2.4 on 2021-06-03 19:53

from django.db import migrations
from django.db import models

import core.files


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diploma',
            name='image',
            field=models.ImageField(upload_to=core.files.RandomFileName('diplomas')),
        ),
    ]
