# Generated by Django 3.2.4 on 2021-06-04 13:00

import shortuuid
from django.db import migrations, models


def rename_old_slugs(apps, schema_editor):
    del schema_editor

    for diploma in apps.get_model("diplomas.Diploma").objects.all():
        diploma.slug = shortuuid.uuid()
        diploma.save()


class Migration(migrations.Migration):
    dependencies = [
        ("diplomas", "0002_RandomDiplomaFileNames"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diploma",
            name="slug",
            field=models.CharField(db_index=True, default=shortuuid.uuid, max_length=32, unique=True),
        ),
        migrations.RunPython(rename_old_slugs),
    ]
