# Generated by Django 3.2.4 on 2021-09-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_ProductGroups"),
        ("diplomas", "0003_ShortDiplomaSlug"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiplomaTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("slug", models.CharField(help_text="Check out https://is.gd/eutOYr for available templates", max_length=32)),
                ("with_homework", models.BooleanField(verbose_name="With homework")),
                ("language", models.CharField(choices=[("RU", "Russian"), ("EN", "English")], db_index=True, max_length=3)),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="products.course")),
            ],
            options={
                "verbose_name": "Diploma template",
                "verbose_name_plural": "Diploma templates",
            },
        ),
        migrations.AddIndex(
            model_name="diplomatemplate",
            index=models.Index(fields=["course", "with_homework", "language"], name="diplomas_di_course__b710b3_idx"),
        ),
        migrations.AddConstraint(
            model_name="diplomatemplate",
            constraint=models.UniqueConstraint(fields=("course", "with_homework", "language"), name="single diploma per course option"),
        ),
    ]
