# Generated by Django 4.2.6 on 2023-11-01 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("diplomas", "0006_DiplomaTemplateHomework"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diploma",
            options={
                "default_related_name": "diplomas",
                "ordering": ["-id"],
                "permissions": [("access_all_diplomas", "May access diplomas of all students")],
                "verbose_name": "Diploma",
                "verbose_name_plural": "Diplomas",
            },
        ),
    ]
