# Generated by Django 4.2.6 on 2023-11-03 21:26


from django.db import migrations
from django.db import models
import django.db.models.deletion

import core.files


class Migration(migrations.Migration):
    dependencies = [
        ("studying", "0003_add_verbose_names"),
        ("diplomas", "0006_DiplomaTemplateHomework"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiplomaStudyProxy",
            fields=[],
            options={
                "verbose_name": "Manual upload",
                "verbose_name_plural": "Manual uploads",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("studying.study",),
        ),
        migrations.AlterModelOptions(
            name="diploma",
            options={
                "default_related_name": "diplomas",
                "ordering": ["-id"],
                "permissions": [("access_all_diplomas", "May access diplomas of all students")],
                "verbose_name": "Diploma",
                "verbose_name_plural": "Diplomas",
            },
        ),
        migrations.AlterField(
            model_name="diploma",
            name="image",
            field=models.ImageField(upload_to=core.files.RandomFileName("diplomas"), verbose_name="Image"),
        ),
        migrations.AlterField(
            model_name="diploma",
            name="language",
            field=models.CharField(choices=[("RU", "Russian"), ("EN", "English")], db_index=True, max_length=3, verbose_name="Language"),
        ),
        migrations.AlterField(
            model_name="diploma",
            name="study",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studying.study", verbose_name="Study"),
        ),
    ]
