# Generated by Django 4.2.23 on 2025-07-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplomas', '0007_set_default_related_name_and_verbose_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diplomatemplate',
            name='slug',
            field=models.CharField(max_length=32),
        ),
    ]
