# fmt: off
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.messages",
    "django.contrib.sessions",
    "django.contrib.staticfiles",

    "anymail",
    "axes",
    "corsheaders",
    "debug_toolbar",
    "dj_rest_auth",
    "django_filters",
    "drf_recaptcha",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "prettyjson",
    "rest_framework",
    "rest_framework.authtoken",

    "apps.a12n",
    "apps.amocrm",
    "apps.banking",
    "apps.chains",
    "apps.diplomas",
    "apps.homework",
    "apps.magnets",
    "apps.mailing",
    "apps.notion",
    "apps.orders",
    "apps.products",
    "apps.stripebank",
    "apps.studying",
    "apps.tinkoff",
    "apps.users",

    "core",
]
# fmt: on
