# Generated by Django 3.1.8 on 2021-05-22 21:24

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


def create_study_records_for_all_purcased_courses(apps, schema_editor):
    Study = apps.get_model('studying.Study')
    Order = apps.get_model('orders.Order')

    for order in Order.objects.filter(course__isnull=False, paid__isnull=False):
        Study.objects.get_or_create(
            student=order.user,
            course=order.course,
            defaults=dict(
                order=order,
            ),
        )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0014_NonAttachedPromocodes'),
        ('products', '0018_ProductGroups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.course')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='study',
            index=models.Index(fields=['student', 'course'], name='studying_st_student_31a713_idx'),
        ),
        migrations.AddConstraint(
            model_name='study',
            constraint=models.UniqueConstraint(fields=('student', 'course'), name='unique_student_course_study'),
        ),
        migrations.RunPython(create_study_records_for_all_purcased_courses),
    ]
