# Generated by Django 4.2.6 on 2023-11-03 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studying", "0002_StudyIsHomeworkAccepted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="study",
            options={"verbose_name": "Study", "verbose_name_plural": "Studies"},
        ),
    ]
