# Generated by Django 4.2.21 on 2025-05-14 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studying", "0003_add_verbose_names"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="study",
            options={
                "permissions": [("purchased_all_courses", "May access all courses as if has purchased them")],
                "verbose_name": "Study",
                "verbose_name_plural": "Studies",
            },
        ),
    ]
