# Generated by Django 4.2.20 on 2025-04-28 08:42

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0003_modules"),
    ]

    operations = [
        migrations.CreateModel(
            name="Call",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("url", models.URLField(max_length=255, verbose_name="URL")),
            ],
            options={
                "verbose_name": "Call",
                "verbose_name_plural": "Calls",
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
        migrations.AddField(
            model_name="lesson",
            name="call",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="lms.call", verbose_name="Call"),
        ),
    ]
