# Generated by Django 4.2.20 on 2025-05-13 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_calls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='name',
        ),
    ]
