# Generated by Django 4.2.21 on 2025-05-14 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0004_calls"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="name",
        ),
    ]
