# Generated by Django 4.2.21 on 2025-05-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0005_drop_lesson_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="hidden",
            field=models.BooleanField(default=False, help_text="Users can't find such materials in the listing", verbose_name="Hidden"),
        ),
    ]
