# Generated by Django 4.2.21 on 2025-05-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0006_lesson_is_not_hidden_by_default"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="rutube_access_key",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="call",
            name="rutube_id",
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="call",
            name="youtube_id",
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
