# Generated by Django 4.2.21 on 2025-05-21 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0007_call_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Call date"),
            preserve_default=False,
        ),
    ]
