# Generated by Django 4.2.21 on 2025-05-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0008_call_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="description",
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name="Short description"),
        ),
        migrations.AddField(
            model_name="module",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Text"),
        ),
    ]
