# Generated by Django 4.2.21 on 2025-05-21 19:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0009_module_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="call",
            name="description",
            field=models.CharField(verbose_name="Description", blank=True, max_length=512, null=True),
        ),
    ]
