# Generated by Django 4.2.21 on 2025-05-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0010_call_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="datetime",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Call date"),
        ),
    ]
