# Generated by Django 4.2.21 on 2025-05-27 15:44

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0011_date_not_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("url", models.CharField(max_length=255, verbose_name="URL")),
                ("course", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lms.course")),
            ],
            options={
                "verbose_name": "Course link",
                "verbose_name_plural": "Course links",
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
    ]
