# Generated by Django 4.2.21 on 2025-06-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0012_course_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Start date"),
        ),
    ]
