# Generated by Django 4.2.23 on 2025-08-18 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0024_drop_question_courses_field"),
        ("notion", "0015_better_cache_key_name"),
        ("lms", "0013_module_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="material",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="notion.material", verbose_name="Material"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="question",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="homework.question", verbose_name="Question"),
        ),
    ]
