# Generated by Django 4.2.23 on 2025-08-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0014_question_relation"),
    ]

    operations = [
        migrations.AddField(
            model_name="module",
            name="archived",
            field=models.BooleanField(db_index=True, default=False, help_text="Hidden from the admin, but still acessible by users", verbose_name="Archived"),
        ),
        migrations.AlterField(
            model_name="module",
            name="hidden",
            field=models.BooleanField(db_index=True, default=True, help_text="Users can't find such materials in the listing", verbose_name="Hidden"),
        ),
    ]
