# Generated by Django 4.2.23 on 2025-09-09 07:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lms", "0015_module_archiving"),
    ]

    operations = [
        migrations.AlterField(
            model_name="call",
            name="url",
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name="URL"),
        ),
    ]
