# Generated by Django 3.1.8 on 2021-04-17 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0002_MultipleCourses"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="parent",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="children", to="homework.answer", verbose_name="parent"
            ),
        ),
    ]
