# Generated by Django 3.1.8 on 2021-04-18 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0003_AnswerTree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['created'], 'verbose_name': 'Homework answer', 'verbose_name_plural': 'Homework answers'},
        ),
    ]
