# Generated by Django 3.1.8 on 2021-04-18 13:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0004_DefaultAnswerOrdering"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "ordering": ["created"],
                "permissions": [("see_all_answers", "May see answers from every user")],
                "verbose_name": "Homework answer",
                "verbose_name_plural": "Homework answers",
            },
        ),
    ]
