# Generated by Django 3.1.8 on 2021-04-26 13:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0008_AnswersCrossCheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='do_not_crosscheck',
            field=models.BooleanField(default=False, verbose_name='Exclude from cross-checking'),
        ),
    ]
