# Generated by Django 4.2.13 on 2024-07-05 14:18

import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0013_DropAnswerRelationsForMypyUpgrade"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrossCheckTask",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("answer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="cross_check_tasks", to="homework.answer")),
                (
                    "required_cross_check",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="required_tasks", to="homework.answercrosscheck"),
                ),
                (
                    "source_cross_check",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="source_tasks", to="homework.answercrosscheck"),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["source_cross_check", "answer"], name="homework_cr_source__c00e6a_idx")],
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="crosschecktask",
            constraint=models.UniqueConstraint(fields=("source_cross_check", "answer"), name="unique_source_cross_check_and_answer"),
        ),
    ]
