# Generated by Django 4.2.13 on 2024-07-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0013_DropAnswerRelationsForMypyUpgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="answercrosscheck",
            name="is_checked",
            field=models.BooleanField(default=False, verbose_name="Is checked"),
        ),
    ]
