# Generated by Django 4.2.13 on 2024-07-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0013_DropAnswerRelationsForMypyUpgrade"),
    ]

    operations = [
        migrations.AddField(
            model_name="answercrosscheck",
            name="checked_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date when crosscheck got checked"),
        ),
    ]
