# Generated by Django 4.2.14 on 2024-07-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0014_AnswerCrossCheckCheckedAt"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="hide_crosschecked_answers_from_students_without_checks",
            field=models.BooleanField(default=False, verbose_name="Hide crosschecked answers from students without checks"),
        ),
    ]
