# Generated by Django 4.2.14 on 2024-07-22 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0015_QuestionHideCrossCheckedAnswersFromStudentsWithoutChecks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="hide_crosschecked_answers_from_students_without_checks",
        ),
    ]
