# Generated by Django 4.2.20 on 2025-03-24 08:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def make_a_copy_of_each_question_with_more_then_1_course(apps, schema_editor):  # NOQA: ARG001
    apps.get_model("lessons.Lesson")
    for question in apps.get_model("homework.Question").all():
        courses = question.courses.order_by("created")
        if courses.count() <= 1:
            continue

        for _course in courses[1:]:
            ...


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0001_initial"),
        ("homework", "0017_answer_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="homework.question"),
        ),
        migrations.AddField(
            model_name="question",
            name="lesson",
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to="lessons.lesson"),
            preserve_default=False,
        ),
    ]
