# Generated by Django 4.2.20 on 2025-03-24 08:48
import contextlib
from typing import no_type_check

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


@no_type_check
def migrate_authors_to_study(apps, schema_editor):  # NOQA: ARG001
    Study = apps.get_model("studying.Study")
    Answer = apps.get_model("homework.Answer")

    def find_study(answer):
        for course in answer.question.courses.all():
            with contextlib.suppress(Study.DoesNotExist):
                return Study.objects.get(course=course, student=answer.author)

    for answer in Answer.objects.iterator():
        study = find_study(answer)
        if study is not None:
            answer.study = study
            answer.save()


class Migration(migrations.Migration):
    dependencies = [
        ("studying", "0003_add_verbose_names"),
        ("homework", "0016_QuestionDropHideCrossCheckFlag"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="study",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="studying.study"),
        ),
        migrations.RunPython(migrate_authors_to_study),
    ]
