# Generated by Django 4.2.20 on 2025-03-27 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studying", "0003_add_verbose_names"),
        ("homework", "0017_answer_study"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to="homework.question"),
        ),
        migrations.AlterField(
            model_name="answer",
            name="study",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="studying.study"),
        ),
    ]
