# Generated by Django 4.2.20 on 2025-03-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0018_answer_relations_fix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answercrosscheck",
            name="checked_at",
        ),
        migrations.AddField(
            model_name="answercrosscheck",
            name="checked",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date when crosscheck got checked"),
        ),
    ]
