# Generated by Django 4.2.20 on 2025-03-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0019_rename_checked_at_to_checked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="do_not_crosscheck",
            field=models.BooleanField(db_index=True, default=False, verbose_name="Exclude from cross-checking"),
        ),
        migrations.AlterField(
            model_name="answercrosscheck",
            name="checked",
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="Date when crosscheck got checked"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["question", "author"], name="homework_an_questio_45c299_idx"),
        ),
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["question", "study"], name="homework_an_questio_0e5ab9_idx"),
        ),
        migrations.AddIndex(
            model_name="answercrosscheck",
            index=models.Index(fields=["answer", "checker", "checked"], name="homework_an_answer__3fe5c4_idx"),
        ),
    ]
