# Generated by Django 4.2.20 on 2025-03-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0020_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Deadline"),
        ),
    ]
