# Generated by Django 4.2.21 on 2025-05-26 19:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0021_question_deadline"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnswerAccessLogEntry",
        ),
    ]
