# Generated by Django 4.2.23 on 2025-08-18 10:28

import django.db.models.deletion
from django.db import migrations, models


# type: ignore
def populate_legacy_course_id(apps, schema_editor):  # NOQA: ARG001
    for question in apps.get_model("homework.Question").objects.all():
        course = question.courses.first()
        if course is not None:
            question._legacy_course = course
            question.save(update_fields=["_legacy_course"])


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0022_drop_answer_acess_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="_legacy_course",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="products.course"),
        ),
        migrations.RunPython(populate_legacy_course_id),
        migrations.RemoveField(
            model_name="question",
            name="courses",
        ),
    ]
