# Generated by Django 4.2.23 on 2025-08-21 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0022_drop_answer_acess_log"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="answer",
            index=models.Index(fields=["parent_id", "created"], name="homework_an_parent__842310_idx"),
        ),
    ]
