# Generated by Django 4.2.23 on 2025-08-18 10:28
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


# type: ignore
def populate_legacy_course_id(apps, schema_editor):  # NOQA: ARG001
    for question in apps.get_model("homework.Question").objects.all():
        course_ids = question.courses.values_list("id", flat=True)
        if course_ids.exists():
            question._legacy_courses = list(course_ids)
            question.save(update_fields=["_legacy_courses"])


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0023_answer_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="_legacy_courses",
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None),
        ),
        migrations.RunPython(populate_legacy_course_id),
        migrations.RemoveField(
            model_name="question",
            name="courses",
        ),
    ]
