# Generated by Django 4.2.23 on 2025-08-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0024_drop_question_courses_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="content",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
