# Generated by Django 4.2.23 on 2025-09-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0025_answer_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="archived",
            field=models.BooleanField(db_index=True, default=False, help_text="Hidden from the admin, but still acessible by users", verbose_name="Archived"),
        ),
    ]
