# Generated by Django 4.2.23 on 2025-09-24 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0026_homework_archive"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answercrosscheck",
            options={"ordering": ["id"]},
        ),
    ]
