# Generated by Django 5.2.7 on 2025-10-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0027_crosscheck_default_ordering"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
