# Generated by Django 5.2.7 on 2025-11-03 14:34

from django.db import migrations, models


def set_internal_name(apps, schema_editor) -> None:  # NOQA: ARG001
    Question = apps.get_model("homework.Question")
    Course = apps.get_model("products.Course")
    Lesson = apps.get_model("lms.Lesson")

    Question.objects.update(internal_name=models.F("name"))  # set the name by default

    for question in Question.objects.filter(_legacy_courses__isnull=False):
        course = Course.objects.get(pk=question._legacy_courses[0])
        if course.tariff_name is not None:
            question.internal_name = f"{course.product_name} {course.tariff_name}: {question.internal_name}"
        else:
            question.internal_name = f"{course.group.name}: {question.internal_name}"

        question.save(update_fields=["internal_name"])

    for question in Question.objects.filter(_legacy_courses__isnull=True):
        lesson = Lesson.objects.filter(question=question).first()

        if lesson is None:
            continue

        course = lesson.module.course

        question.internal_name = f"{course.group.name} {course.tariff_name}: {question.internal_name}"
        question.save(update_fields=["internal_name"])


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0028_answer_inheritance_fix"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="internal_name",
            field=models.CharField(null=True, max_length=256, verbose_name="Internal name"),
        ),
        migrations.RunPython(set_internal_name),
        migrations.AlterField(
            model_name="question",
            name="internal_name",
            field=models.CharField(max_length=256, verbose_name="Internal name"),
        ),
    ]
