# Generated by Django 5.2.7 on 2025-12-04 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0029_question_internal_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="answer",
            old_name="text",
            new_name="legacy_text",
        ),
    ]
