# Generated by Django 5.2.10 on 2026-01-24 16:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def set_default_crosscheck_author(apps, schema_editor) -> None:  # NOQA: ARG001
    apps.get_model("homework.AnswerCrossCheck").objects.update(
        author=models.F("checker"),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0030_answer_legacy_text_field_renamed"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answercrosscheck",
            name="author",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(set_default_crosscheck_author),
        migrations.AlterField(
            model_name="answercrosscheck",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name="answercrosscheck",
            name="checker",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL),
        ),
    ]
