# Generated by Django 5.2.10 on 2026-01-24 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.files
import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0031_crosscheck_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerAttachment",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("file", models.FileField(upload_to=core.files.RandomFileName("homework/attachments"))),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
    ]
