# Generated by Django 2.2.13 on 2020-09-27 16:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_PromoCodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
