# Generated by Django 3.1.6 on 2021-02-06 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_DesiredBankString'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='desired_bank',
        ),
    ]
