# Generated by Django 3.2.8 on 2021-10-23 23:23

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_PromoCodeValue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='unpaid',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date when order got unpaid'),
        ),
    ]
