# Generated by Django 3.2.10 on 2021-12-27 20:39

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_OrderAuthorMigrationFix'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=django.db.models.expressions.RawSQL(output_field=models.BooleanField(), params=[], sql="(CAST(coalesce(course_id, '0') AS integer) +\n                        CAST(coalesce(bundle_id, '0') AS integer) + CAST(coalesce(record_id, '0') AS integer)) <= 1"), name='check_product_items'),
        ),
    ]
