# Generated by Django 4.2.5 on 2023-09-15 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0031_Drop_o2o_properties_from_amocrm_lead_and_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanReadableOrder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("orders.order",),
        ),
    ]
