# Generated by Django 4.2.5 on 2023-09-23 16:14

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0031_Drop_o2o_properties_from_amocrm_lead_and_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="bank_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dolyame", "Долями"),
                    ("stripe", "Страйп"),
                    ("tinkoff_bank", "Тинькофф"),
                    ("tinkoff_credit", "Т.Кредит"),
                    ("zero_price", "Бесплатно"),
                ],
                max_length=32,
                verbose_name="User-requested bank string",
            ),
        ),
    ]
