# Generated by Django 4.2.5 on 2023-09-20 17:30

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0031_Drop_o2o_properties_from_amocrm_lead_and_transaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refund",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("author_ip", models.GenericIPAddressField()),
                ("bank_confirmation_received", models.BooleanField(default=False, verbose_name="Bank refund confirmation")),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name="refunds", to=settings.AUTH_USER_MODEL)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="refunds", to="orders.order")),
            ],
            options={
                "verbose_name": "Refund",
                "verbose_name_plural": "Refunds",
                "ordering": ["-created"],
            },
        ),
    ]
