# Generated by Django 4.2.5 on 2023-09-22 11:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0032_order_refund_log_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="bank_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dolyame", "Долями"),
                    ("stripe", "Страйп"),
                    ("tinkoff_bank", "Тинькофф"),
                    ("tinkoff_credit", "Т.Кредит"),
                    ("zero_price", "Бесплатно"),
                ],
                max_length=32,
                verbose_name="User-requested bank string",
            ),
        ),
    ]
