# Generated by Django 3.1.4 on 2021-01-02 18:09

from django.db import migrations


def drop_old_contenttypes(apps, schema_editor):
    del schema_editor

    apps.get_model("contenttypes.ContentType").objects.filter(app_label="onetime").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_CourseMailLog"),
    ]

    operations = [
        migrations.RunPython(drop_old_contenttypes),
        migrations.RunSQL("DROP TABLE IF EXISTS onetime_token;"),
    ]
