# Generated by Django 3.1.4 on 2021-01-03 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_DropTheOnetimeApp'),
    ]

    operations = [
        migrations.RunSQL("UPDATE django_migrations SET app='products' WHERE app='courses';"),
    ]
