# Generated by Django 3.2.13 on 2022-06-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_RenameCoursesAppPt1'),
        ('mailing', '0001_EmailLogEntryMovedToDedicatedApp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLogEntry',
        ),
    ]
