# Generated by Django 3.1.7 on 2021-04-15 19:49

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_TinkoffCreditPromoCode'),
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.AddField(
            model_name='question',
            name='courses',
            field=models.ManyToManyField(to='products.Course'),
        ),
    ]
