# Generated by Django 3.1.8 on 2021-04-20 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_SeeAllQuestionsPermission'),
        ('homework', '0006_AnswerAccessLogEntry'),
    ]

    operations = [
    ]
