# Generated by Django 4.1.7 on 2023-05-10 05:37

from django.conf import settings
from django.db import migrations
from django.db import models
import django.db.models.deletion

import app.files


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("homework", "0010_ForogttenAnswerModified"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnswerImage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("image", models.ImageField(upload_to=app.files.RandomFileName("homework/answers"))),
                ("author", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
