INSTALLED_APPS = [
    'a12n',
    'app',
    'banking',
    'diplomas',
    'homework',
    'magnets',
    'notion',
    'orders',
    'products',
    'studying',
    'tinkoff',
    'triggers',
    'users',
    'chains',

    'markdownx',
    'corsheaders',
    'cachalot',
    'hattori',
    'anymail',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_recaptcha',
    'django_filters',

    'axes',
    'debug_toolbar',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
