# Generated by Django 2.2.7 on 2019-11-08 15:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('terminal_key', models.CharField(max_length=512)),
                ('order_id', models.IntegerField()),
                ('success', models.BooleanField()),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('CONFIRMED', 'Confirmed'), ('REVERSED', 'Reversed'), ('REFUNDED', 'Refunded'), ('PARTIAL_REFUNDED', 'Partial refunded'), ('REJECTED', 'Rejected')], max_length=128)),
                ('payment_id', models.BigIntegerField()),
                ('error_code', models.CharField(max_length=512, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rebill_id', models.BigIntegerField(null=True)),
                ('card_id', models.IntegerField()),
                ('pan', models.CharField(max_length=128, null=True)),
                ('data', models.TextField(null=True)),
                ('token', models.CharField(max_length=512)),
                ('exp_date', models.CharField(max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
