# Generated by Django 2.2.7 on 2019-11-19 16:10

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentnotification',
            name='card_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
