# Generated by Django 3.1.6 on 2021-02-06 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tinkoff", "0002_EmptyCardID"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNotification",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("order_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected"), ("canceled", "Canceled"), ("signed", "Signed")], max_length=32
                    ),
                ),
                ("bank_created", models.DateTimeField()),
                ("first_payment", models.DecimalField(decimal_places=2, max_digits=10)),
                ("order_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("credit_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("product", models.CharField(max_length=128)),
                ("term", models.IntegerField()),
                ("monthly_payment", models.DecimalField(decimal_places=2, max_digits=10)),
                ("phone", models.CharField(blank=True, max_length=64, null=True)),
                ("first_name", models.CharField(blank=True, max_length=128, null=True)),
                ("last_name", models.CharField(blank=True, max_length=128, null=True)),
                ("middle_name", models.CharField(blank=True, max_length=32, null=True)),
                ("loan_number", models.CharField(blank=True, max_length=128, null=True)),
                ("email", models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
