# Generated by Django 3.2.12 on 2022-05-16 10:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkoff', '0004_DolyameNotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dolyamenotification',
            name='status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled'), ('committed', 'Committed'), ('wait_for_commit', 'Waiting for commit'), ('completed', 'Completed')], max_length=32),
        ),
    ]
