# Generated by Django 4.2.7 on 2023-11-18 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tinkoff", "0009_DolyameOrderUUID"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CreditNotification",
        ),
    ]
