# Generated by Django 4.2.6 on 2023-11-17 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tinkoff", "0009_DolyameOrderUUID"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CreditNotification",
        ),
    ]
