# Generated by Django 4.2.6 on 2023-11-04 16:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Receipt",
        ),
    ]
