# Generated by Django 4.2.17 on 2024-12-24 10:08

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("banking", "0002_drop_recipient_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Currency name in ISO 4217 format. E.g. USD", max_length=4, unique=True)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Rate")),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
    ]
