# Generated by Django 4.2.17 on 2024-12-24 18:15
from decimal import Decimal

from django.db import migrations, models

import core.models


def create_currencies(apps, schema_editor):
    del schema_editor

    CurrencyRate = apps.get_model("banking.CurrencyRate")

    CurrencyRate.objects.create(name="RUB", rate=Decimal(1))
    CurrencyRate.objects.create(name="USD", rate=Decimal(90))
    CurrencyRate.objects.create(name="KZT", rate=Decimal("0.18"))
    CurrencyRate.objects.create(name="KIS", rate=Decimal(1))


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("banking", "0002_drop_recipient_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        choices=[("RUB", "RUB"), ("USD", "USD"), ("KZT", "KZT"), ("KIS", "KIS (for zero-price orders)")],
                        db_index=True,
                        max_length=4,
                        unique=True,
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Rate")),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
        migrations.RunPython(create_currencies),
    ]
