# Generated by Django 4.2.17 on 2024-12-25 13:38
from decimal import Decimal

from django.db import migrations, models

import core.models


def create_acquiring_percents(apps, schema_editor):
    del schema_editor

    Acquiring = apps.get_model("banking.Acquiring")

    Acquiring.objects.create(bank="tinkoff_bank", percent=Decimal("2.79"))
    Acquiring.objects.create(bank="stripe", percent=Decimal(4))
    Acquiring.objects.create(bank="stripe_kz", percent=Decimal(4))
    Acquiring.objects.create(bank="dolyame", percent=Decimal("6.9"))
    Acquiring.objects.create(bank="zero_price", percent=Decimal(0))


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acquiring",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("tinkoff_bank", "Tinkoff"),
                            ("stripe", "Stripe USD"),
                            ("stripe_kz", "Stripe KZT"),
                            ("dolyame", "Dolyame"),
                            ("zero_price", "Zero Price"),
                        ],
                        db_index=True,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("percent", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "verbose_name": "Acquiring percent",
                "verbose_name_plural": "Acquiring percents",
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
        migrations.RunPython(create_acquiring_percents),
    ]
