# Generated by Django 4.2.17 on 2024-12-25 13:38

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Acquiring",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "bank",
                    models.CharField(
                        choices=[
                            ("tinkoff_bank", "Tinkoff"),
                            ("stripe", "Stripe USD"),
                            ("stripe_kz", "Stripe KZT"),
                            ("dolyame", "Dolyame"),
                            ("zero_price", "Zero Price"),
                        ],
                        db_index=True,
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("percent", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "verbose_name": "Acquiring percent",
                "verbose_name_plural": "Acquiring percents",
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
    ]
