# Generated by Django 4.2.20 on 2025-04-30 14:59

import django.utils.timezone
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcquiringPercent",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("slug", models.CharField(db_index=True, max_length=60, unique=True)),
                ("percent", models.DecimalField(decimal_places=2, max_digits=9, verbose_name="Percent")),
            ],
            options={
                "abstract": False,
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name="acquiringpercent",
            options={"verbose_name": "Acquiring percent", "verbose_name_plural": "Acquiring percents"},
        ),
        migrations.AddField(
            model_name="currencyrate",
            name="created",
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="currencyrate",
            name="modified",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
