# Generated by Django 4.2.23 on 2025-07-15 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0004_acquiring_percent"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CurrencyRate",
            new_name="Currency",
        ),
    ]
