# Generated by Django 5.2.7 on 2025-10-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("banking", "0005_rename_currency_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="name",
            field=models.CharField(
                choices=[("RUB", "RUB"), ("USD", "USD"), ("EUR", "EUR"), ("KZT", "KZT"), ("KIS", "KIS (for zero-price orders)")],
                db_index=True,
                max_length=4,
                unique=True,
            ),
        ),
    ]
