# Generated by Django 4.1.10 on 2023-08-25 04:48

from django.db import migrations
from django.db import models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0029_DropGiftFields"),
        ("amocrm", "0004_Add_AmoCRM_leads_and_transactions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amocrmorderlead",
            name="order",
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="orders.order"),
        ),
        migrations.AlterField(
            model_name="amocrmordertransaction",
            name="order",
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to="orders.order"),
        ),
    ]
