# Generated by Django 4.1.10 on 2023-08-30 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amocrm", "0007_Move_contact_id_to_AmoCRMUser"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AmoCRMUserContact",
        ),
    ]
