# Generated by Django 4.1.10 on 2023-09-04 03:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amocrm", "0008_Delete_separate_AmoCRMUserContact"),
        ("products", "0032_Move_amocrm_id_into_main_Group_model"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AmoCRMProductGroup",
        ),
    ]
