# Generated by Django 2.2.7 on 2019-12-22 14:46

from django.db import migrations
import django.db.models.deletion

import apps.orders.fields
import apps.orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_Bundles'),
        ('orders', '0002_L18N'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bundle',
            field=apps.orders.fields.ItemField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.Bundle'),
        ),
    ]
