# Generated by Django 2.2.13 on 2020-09-30 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_PromoCodeComments"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="promocode",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="orders.PromoCode"),
        ),
    ]
