# Generated by Django 3.1.7 on 2021-04-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_TinkoffCreditPromoCode"),
        ("orders", "0012_DesiredBankString"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="courses",
            field=models.ManyToManyField(help_text="Can not be used for courses not checked here", to="products.Course"),
        ),
    ]
