# Generated by Django 3.2.8 on 2021-11-25 20:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def set_order_author(apps, schema_editor):
    del schema_editor

    LogEntry = apps.get_model("admin.LogEntry")
    Order = apps.get_model("orders.Order")

    for order in Order.objects.filter(author__isnull=True).iterator():
        admin_log_entry = LogEntry.objects.filter(content_type=11, action_flag=1, object_id=order.pk).first()

        if admin_log_entry:
            order.author = admin_log_entry.user
        else:
            order.author = order.user

        order.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0018_StudentProxyModel"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, related_name="created_orders", to="users.user", verbose_name="Order author"
            ),
        ),
        migrations.RunPython(set_order_author),
        migrations.AlterField(
            model_name="order",
            name="author",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_orders", to="users.user", verbose_name="Order author"),
        ),
    ]
