# Generated by Django 3.2.13 on 2022-06-26 11:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0024_OrderSlugs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="desired_bank",
            new_name="bank_id",
        ),
    ]
