# Generated by Django 3.2.16 on 2022-10-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0025_BankFieldRename"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocode",
            name="expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
