# Generated by Django 4.1.7 on 2023-04-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0027_PromocodeDestinationField"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocode",
            name="expires",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Expiration date"),
        ),
    ]
