# Generated by Django 4.1.10 on 2023-07-18 08:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0028_PromocodeExpiresFieldTranslation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="desired_shipment_date",
        ),
        migrations.RemoveField(
            model_name="order",
            name="gift_message",
        ),
        migrations.RemoveField(
            model_name="order",
            name="giver",
        ),
        migrations.RemoveField(
            model_name="order",
            name="notification_to_giver_is_sent",
        ),
    ]
