# Generated by Django 4.1.10 on 2023-08-25 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0030_Add_lead_and_transaction_to_Order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="amocrm_lead",
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order", to="amocrm.amocrmorderlead"),
        ),
        migrations.AlterField(
            model_name="order",
            name="amocrm_transaction",
            field=models.OneToOneField(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order", to="amocrm.amocrmordertransaction"
            ),
        ),
    ]
