# Generated by Django 4.2.5 on 2023-09-25 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0031_Drop_o2o_properties_from_amocrm_lead_and_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="bank_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dolyame", "Dolyame"),
                    ("stripe", "Stripe"),
                    ("tinkoff_bank", "Tinkoff"),
                    ("tinkoff_credit", "Tinkoff Credit"),
                    ("zero_price", "Zero Price"),
                ],
                max_length=32,
                verbose_name="User-requested bank string",
            ),
        ),
    ]
