# Generated by Django 4.2.6 on 2023-11-17 09:31

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0032_order_set_bank_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="bank_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dolyame", "Dolyame"),
                    ("stripe", "Stripe"),
                    ("tinkoff_bank", "Tinkoff"),
                    ("zero_price", "Zero Price"),
                ],
                max_length=32,
                verbose_name="User-requested bank string",
            ),
        ),
    ]
