# Generated by Django 4.2.7 on 2023-11-20 20:15

from django.db import migrations
from django.db import models


def set_manual_bank_to_paid_orders_without_bank(apps, schema_editor):
    Order = apps.get_model("orders", "Order")

    paid_orders_without_bank = Order.objects.filter(
        bank_id="",
        paid__isnull=False,
    )

    paid_orders_without_bank.update(bank_id="manual")


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0033_DropTinkoffCreditFromBankChoices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="bank_id",
            field=models.CharField(
                blank=True,
                choices=[("dolyame", "Dolyame"), ("manual", "Manual"), ("stripe", "Stripe"), ("tinkoff_bank", "Tinkoff"), ("zero_price", "Zero Price")],
                max_length=32,
                verbose_name="User-requested bank string",
            ),
        ),
        migrations.RunPython(set_manual_bank_to_paid_orders_without_bank),
    ]
