# Generated by Django 4.2.6 on 2023-12-02 12:54

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0033_DropTinkoffCreditFromBankChoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="analytics",
            field=models.JSONField(default=dict),
        ),
    ]
