# Generated by Django 4.2.8 on 2024-01-01 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0034_AnalyticsMetadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date when order got paid"),
        ),
    ]
