# Generated by Django 4.2.11 on 2024-03-22 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0035_drop_paid_date_helptext"),
    ]

    operations = [
        migrations.CreateModel(
            name="Refund",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=9, verbose_name="Amount")),
                (
                    "bank_id",
                    models.CharField(
                        blank=True,
                        choices=[("dolyame", "Dolyame"), ("stripe", "Stripe"), ("tinkoff_bank", "Tinkoff"), ("zero_price", "Zero Price")],
                        max_length=32,
                        verbose_name="Order bank at the moment of refund",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_refunds",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="refunds", to="orders.order", verbose_name="Order")),
            ],
            options={
                "verbose_name": "Refund",
                "verbose_name_plural": "Refunds",
            },
            bases=(core.models.TestUtilsMixin, models.Model),
        ),
    ]
