# Generated by Django 4.2.11 on 2024-03-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0035_drop_paid_date_helptext"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refund_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name="Refund amount"),
        ),
    ]
