# Generated by Django 4.2.11 on 2024-03-27 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0036_Refund"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="unpaid",
        ),
    ]
