# Generated by Django 4.2.17 on 2024-12-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0038_alter_order_bank_id_alter_refund_bank_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="ue_rate",
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name="Purchase-time UE rate"),
        ),
    ]
