# Generated by Django 4.2.19 on 2025-03-04 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0001_initial"),
        ("orders", "0039_alter_order_ue_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deal",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="b2b.deal", verbose_name="Deal"),
        ),
    ]
