# Generated by Django 4.2.20 on 2025-03-09 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2b", "0001_initial"),
        ("orders", "0039_alter_order_ue_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deal",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="b2b.deal", verbose_name="Deal"),
        ),
        migrations.AlterField(
            model_name="order",
            name="bank_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("b2b", "B2B Bank"),
                    ("dolyame", "Dolyame"),
                    ("stripe", "Stripe USD"),
                    ("stripe_kz", "Stripe KZT"),
                    ("tinkoff_bank", "Tinkoff"),
                    ("zero_price", "Zero Price"),
                ],
                max_length=32,
                verbose_name="User-requested bank string",
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="bank_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("b2b", "B2B Bank"),
                    ("dolyame", "Dolyame"),
                    ("stripe", "Stripe USD"),
                    ("stripe_kz", "Stripe KZT"),
                    ("tinkoff_bank", "Tinkoff"),
                    ("zero_price", "Zero Price"),
                ],
                max_length=32,
                verbose_name="Order bank at the moment of refund",
            ),
        ),
    ]
