# Generated by Django 4.2.20 on 2025-04-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0040_b2b"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="acquiring_percent",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name="Acquiring percent"),
        ),
        migrations.AlterField(
            model_name="order",
            name="ue_rate",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name="Purchase-time UE rate"),
        ),
    ]
