# Generated by Django 4.2.20 on 2025-05-03 11:28

from django.db import migrations, models
from django.db.models import F, Q


def set_adhoc_bank(apps, schema_editor):  # NOQA: ARG001
    apps.get_model("orders.Order").objects.filter(
        Q(bank_id__isnull=True) | Q(bank_id=""),
    ).filter(
        price=0,
    ).exclude(
        user_id=F("author_id"),
    ).update(bank_id="adhoc")


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0041_default_ue_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="bank_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("adhoc", "Adhoc"),
                    ("b2b", "B2B Bank"),
                    ("dolyame", "Dolyame"),
                    ("stripe", "Stripe USD"),
                    ("stripe_kz", "Stripe KZT"),
                    ("tinkoff_bank", "Tinkoff"),
                    ("zero_price", "Zero Price"),
                ],
                max_length=32,
                verbose_name="User-requested bank string",
            ),
        ),
        migrations.AlterField(
            model_name="refund",
            name="bank_id",
            field=models.CharField(
                blank=True,
                choices=[
                    ("adhoc", "Adhoc"),
                    ("b2b", "B2B Bank"),
                    ("dolyame", "Dolyame"),
                    ("stripe", "Stripe USD"),
                    ("stripe_kz", "Stripe KZT"),
                    ("tinkoff_bank", "Tinkoff"),
                    ("zero_price", "Zero Price"),
                ],
                max_length=32,
                verbose_name="Order bank at the moment of refund",
            ),
        ),
        migrations.RunPython(set_adhoc_bank),
    ]
