# Generated by Django 4.2.23 on 2025-06-26 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_admin_user_proxy_model_rename"),
        ("orders", "0041_default_ue_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="users.adminuserproxy", verbose_name="User"),
        ),
    ]
