# Generated by Django 4.2.20 on 2025-05-03 12:02


from django.db import migrations
from django.db.models import F, Q


def set_default_bank_for_selfpaid_orders(apps, schema_editor):  # NOQA: ARG001
    apps.get_model("orders.Order").objects.filter(
        Q(bank_id__isnull=True) | Q(bank_id=""),
    ).filter(
        price__gt=0,
        user_id=F("author_id"),
    ).update(bank_id="tinkoff_bank")


def set_b2b_bank_for_b2b_orders(apps, schema_editor):  # NOQA: ARG001
    apps.get_model("orders.Order").objects.filter(
        Q(bank_id__isnull=True) | Q(bank_id=""),
    ).filter(
        price__gt=0,
    ).exclude(
        user_id=F("author_id"),
    ).update(bank_id="b2b")


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0042_adhoc_bank"),
    ]

    operations = [
        migrations.RunPython(set_default_bank_for_selfpaid_orders),
        migrations.RunPython(set_b2b_bank_for_b2b_orders),
    ]
