# Generated by Django 4.2.23 on 2025-08-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0042_admin_user_proxy_model_rename"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="raw",
            field=models.JSONField(default=dict),
        ),
    ]
