# Generated by Django 4.2.23 on 2025-07-15 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0042_admin_user_proxy_model_rename"),
        ("orders", "0043_update_old_banks"),
    ]

    operations = []
