# Generated by Django 4.2.23 on 2025-08-24 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0043_add_raw_field"),
        ("orders", "0044_merge_20250715_1519"),
    ]

    operations = []
