# Generated by Django 2.2.7 on 2019-11-08 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_CourseGenitiveName"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ["-id"]},
        ),
    ]
