# Generated by Django 2.2.7 on 2019-11-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_ClickMeeetingRoomURL"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="full_name",
            field=models.CharField(
                default="", help_text="Билет на мастер-класс о TDD или «запись курсов кройки и шитья»", max_length=255, verbose_name="Full name for letters"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="record",
            name="full_name",
            field=models.CharField(default="", help_text="«Запись мастер-класса о TDD»", max_length=255, verbose_name="Full name for letters"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="course",
            name="name_genitive",
            field=models.CharField(help_text="«мастер-класса о TDD». К примеру для записей.", max_length=255, verbose_name="Genitive name"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name_receipt",
            field=models.CharField(
                help_text="«посещение мастер-класса по TDD» или «Доступ к записи курсов кройки и шитья»", max_length=255, verbose_name="Name for receipts"
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="name_receipt",
            field=models.CharField(help_text="«Доступ к записи курсов кройки и шитья»", max_length=255, verbose_name="Name for receipts"),
        ),
    ]
