# Generated by Django 2.2.7 on 2019-11-16 14:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_ShippableFullName"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-id"], "verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="record",
            options={"ordering": ["-id"], "verbose_name": "Record", "verbose_name_plural": "Records"},
        ),
    ]
