# Generated by Django 2.2.7 on 2019-12-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_L18N"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bundle",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("name", models.CharField(max_length=255)),
                ("name_receipt", models.CharField(help_text="«Доступ к записи курсов кройки и шитья»", max_length=255, verbose_name="Name for receipts")),
                ("slug", models.SlugField()),
                ("full_name", models.CharField(help_text="«Запись мастер-класса о TDD»", max_length=255, verbose_name="Full name for letters")),
                ("courses", models.ManyToManyField(to="products.Course")),
                ("records", models.ManyToManyField(to="products.Record")),
            ],
            options={
                "verbose_name": "Bundle",
                "verbose_name_plural": "Bundles",
                "ordering": ["-id"],
                "db_table": "courses_bundle",
            },
        ),
    ]
