# Generated by Django 2.2.7 on 2020-04-14 19:20

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_Price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='zoomus_webinar_id',
            field=models.CharField(blank=True, help_text='If set, every user who purcashes this course gets invited', max_length=255, null=True, verbose_name='Zoom.us webinar ID'),
        ),
    ]
