# Generated by Django 2.2.13 on 2020-09-30 17:02

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_TemplateIdRename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='template_id',
        ),
        migrations.AddField(
            model_name='course',
            name='welcome_letter_template_id',
            field=models.CharField(blank=True, help_text='Will be sent upon purchase if set', max_length=255, null=True, verbose_name='Welcome letter template id'),
        ),
    ]
