# Generated by Django 3.2.12 on 2022-04-30 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0021_removeMailchimpListId"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="clickmeeting_room_url",
        ),
    ]
