# Generated by Django 3.2.12 on 2022-06-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0022_DitchClickmeetings"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="diploma_template_context",
            field=models.JSONField(default=dict),
        ),
    ]
