# Generated by Django 3.2.13 on 2022-06-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0023_DiplomaTemplateContext"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="diploma_template_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
