# Generated by Django 3.2.13 on 2022-06-28 16:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_DiplomaTemplateContextIsNotRequired'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='disable_triggers',
            field=models.BooleanField(default=False, verbose_name='Disable all triggers'),
        ),
    ]
