# Generated by Django 4.1.10 on 2023-07-18 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0030_SetUniqieSlugForProducts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="gift_welcome_letter_template_id",
        ),
    ]
