# Generated by Django 4.2.20 on 2025-04-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0033_ProductGroupDashamail"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="evergreen",
            field=models.BooleanField(verbose_name="Evergreen", default=False),
        ),
    ]
