# Generated by Django 4.2.20 on 2025-04-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0034_evergreen_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="calendar",
            field=models.URLField(blank=True, null=True, verbose_name="Calendar URL"),
        ),
        migrations.AddField(
            model_name="course",
            name="chat",
            field=models.URLField(blank=True, null=True, verbose_name="Chat URL"),
        ),
    ]
