# Generated by Django 4.2.21 on 2025-05-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0035_course_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="calendar",
        ),
        migrations.AddField(
            model_name="course",
            name="calendar_google",
            field=models.URLField(blank=True, null=True, verbose_name="Calendar URL (Google)"),
        ),
        migrations.AddField(
            model_name="course",
            name="calendar_ios",
            field=models.URLField(blank=True, null=True, verbose_name="Calendar URL (iOS)"),
        ),
    ]
