# Generated by Django 4.2.23 on 2025-07-25 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0036_two_calendars_per_course"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bundle",
            new_name="LegacyBundle",
        ),
        migrations.RenameModel(
            old_name="Record",
            new_name="LegacyRecord",
        ),
    ]
