# Generated by Django 4.2.23 on 2025-07-25 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0037_rename_bundle_record_to_legacy_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="legacybundle",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="legacybundle",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="legacybundle",
            name="name_international",
        ),
        migrations.RemoveField(
            model_name="legacybundle",
            name="name_receipt",
        ),
        migrations.RemoveField(
            model_name="legacybundle",
            name="old_price",
        ),
        migrations.RemoveField(
            model_name="legacybundle",
            name="price",
        ),
        migrations.RemoveField(
            model_name="legacybundle",
            name="records",
        ),
        migrations.RemoveField(
            model_name="legacybundle",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="legacybundle",
            name="tinkoff_credit_promo_code",
        ),
        migrations.RemoveField(
            model_name="legacyrecord",
            name="course",
        ),
        migrations.RemoveField(
            model_name="legacyrecord",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="legacyrecord",
            name="name_international",
        ),
        migrations.RemoveField(
            model_name="legacyrecord",
            name="name_receipt",
        ),
        migrations.RemoveField(
            model_name="legacyrecord",
            name="old_price",
        ),
        migrations.RemoveField(
            model_name="legacyrecord",
            name="price",
        ),
        migrations.RemoveField(
            model_name="legacyrecord",
            name="s3_object_id",
        ),
        migrations.RemoveField(
            model_name="legacyrecord",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="legacyrecord",
            name="template_id",
        ),
        migrations.RemoveField(
            model_name="legacyrecord",
            name="tinkoff_credit_promo_code",
        ),
    ]
