# Generated by Django 4.2.23 on 2025-07-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0039_split_course_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="purchase_success_url",
            field=models.URLField(blank=True, null=True, verbose_name="Purchase success URL"),
        ),
    ]
