# Generated by Django 4.2.23 on 2025-07-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0040_add_purchase_success_url_to_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="homework_check_recommendations",
            field=models.TextField(blank=True, verbose_name="Homework check recommendations"),
        ),
    ]
