# Generated by Django 4.2.23 on 2025-08-27 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0041_course_homework_check_recommendations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "Product group", "verbose_name_plural": "Product groups"},
        ),
        migrations.AlterField(
            model_name="course",
            name="group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.group", verbose_name="Product group"),
        ),
        migrations.AlterField(
            model_name="legacybundle",
            name="group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.group", verbose_name="Product group"),
        ),
        migrations.AlterField(
            model_name="legacyrecord",
            name="group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="products.group", verbose_name="Product group"),
        ),
    ]
