# Generated by Django 4.2.23 on 2025-09-17 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0042_proudct_group_verbose_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="name_international",
            field=models.CharField(max_length=255, verbose_name="Name used for international purchases"),
        ),
    ]
