# Generated by Django 5.2.7 on 2026-01-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0043_required_international_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="end_date",
            field=models.DateField(blank=True, null=True, verbose_name="End date(official)"),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Start date (official)"),
        ),
    ]
