# Generated by Django 4.1.10 on 2023-08-01 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0031_DropGiftFields"),
        ("amocrm", "0001_AddAmoCRMUser"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmoCRMProductGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("amocrm_id", models.PositiveIntegerField(unique=True)),
                ("group", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="amocrm_group", to="products.group")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AmoCRMCourse",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("amocrm_id", models.PositiveIntegerField(unique=True)),
                ("course", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="amocrm_course", to="products.course")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
