# Generated by Django 4.1.10 on 2023-08-08 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("amocrm", "0002_AddAmoCRMGroup_and_Course"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmoCRMUserContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("modified", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("amocrm_id", models.PositiveIntegerField(unique=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="amocrm_user_contact", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
