# Generated by Django 4.1.10 on 2023-08-25 05:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amocrm", "0005_Add_lead_and_transaction_to_Order"),
        ("orders", "0031_Drop_o2o_properties_from_amocrm_lead_and_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="amocrmorderlead",
            name="order",
        ),
        migrations.RemoveField(
            model_name="amocrmordertransaction",
            name="order",
        ),
    ]
