# Generated by Django 4.1.10 on 2023-08-30 12:05

from django.db import migrations, models


def move_contacts_to_amocrm_user(apps, schema_editor):
    del schema_editor

    for contact in apps.get_model("amocrm.AmoCRMUserContact").objects.all().iterator():
        amocrm_user = contact.user.amocrm_user
        amocrm_user.contact_id = contact.amocrm_id
        amocrm_user.save()


class Migration(migrations.Migration):
    dependencies = [
        ("amocrm", "0006_Drop_o2o_properties_from_amocrm_lead_and_transaction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="amocrmuser",
            old_name="amocrm_id",
            new_name="customer_id",
        ),
        migrations.AddField(
            model_name="amocrmuser",
            name="contact_id",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.RunPython(move_contacts_to_amocrm_user),
        migrations.AlterField(
            model_name="amocrmuser",
            name="contact_id",
            field=models.PositiveIntegerField(null=False, blank=False, unique=True),
        ),
    ]
