# Generated by Django 3.2.13 on 2022-06-22 20:14
from django.db import migrations
from django.db import models
from django.db.models import F
from django.db.models import Value
import django.db.models.deletion
from django.db.models.functions import Cast
from django.db.models.functions import Replace
import django.utils.timezone


def delete_orders_that_do_not_belong_to_us(apps, schema_editor):
    """We had some notifications from not ours-orders during the war start when we had europe legal entity

    Let's remove them now
    """
    apps.get_model('stripebank.StripeNotification').objects.exclude(
        old_order_id__icontains='tds-',
    ).delete()


def link_orders(apps, schema_editor):
    apps.get_model('stripebank.StripeNotification').objects.update(
        order_id=Cast(
            Replace(F('old_order_id'), Value('tds-'), Value('')),
            output_field=models.IntegerField(),
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ('orders', '0024_OrderSlugs'),
        ('stripebank', '0001_Initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripenotification',
            old_name='order_id',
            new_name='old_order_id',
        ),
        migrations.AddField(
            model_name='stripenotification',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stripe_notifications', to='orders.order'),
        ),
        migrations.RunPython(delete_orders_that_do_not_belong_to_us),
        migrations.RunPython(link_orders),
        migrations.AlterField(
            model_name='stripenotification',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stripe_notifications', to='orders.order'),
        ),
        migrations.RemoveField(
            model_name='stripenotification',
            name='old_order_id',
        ),
    ]
